services:
  nodejs-code:
    build: 
      dockerfile: docker/Dockerfile.production
      context: .
    environment:
      DB_HOST: mysql  # Use 'host.docker.internal' to connect to the host machine
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes: 
      - ./:/nodejs/
      - nodejs_data:/nodejs/src/public
    depends_on:
      mysql: 
        condition: service_healthy
    ports:
      - ${PORT}:3002
  mysql: 
    image: mysql:8.0
    volumes:
      - db_mysql:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 33061:3306
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', '$$MYSQL_USER', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 2s
      timeout: 8s
      retries: 10
      start_period: 0s
  
volumes:
  db_mysql: 
  nodejs_data:
